valid_assets:
- 1.19.0
- 1.19.1
- 1.19.2
- 1.19.3
- 1.19.4
- 1.19.5
- 1.19.6
- 1.19.7
- 1.19.8
- 1.19.9
- 1.19.13
- 1.19.14
- 1.19.15
- 1.19.16
- 1.19.17
- 1.19.18
- 1.19.19
- 1.19.21
- 1.19.22
- 1.19.23
- 1.19.24
- 1.19.25
- 1.19.26
- 1.19.27
- 1.19.28
- 1.19.29
- 1.19.30
- 1.19.31
- 1.19.32
- 1.19.33
- 1.19.35
- 1.19.36
- 1.19.37
